baseurl = "https://genopretkbh.dukop.dk/"
languageCode = "da"
DefaultContentLanguage = "da"
title = "Genopret Kbh"
theme = "creative"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Genopret Kbh"
	description = "Genopret Kbh er et netv√¶rk for genoprettende cirkler og retf√¶rdighed i K√∏benhavn"

	# The path must be relative to the static folder
	favicon = "uploads/kreds.png"

    # Language
    
    [languages]
        [languages.da]
            title = "Genopret Kbh"
            weight = 1
            [languages.da.params]

        [languages.en]
            title = "Restore Cph"
            weight = 2
            [languages.en.params]

# ENGELSK VERSION

        # Navigation
            [languages.en.params.navigation]
                brand = "Restore Cph"

            [languages.en.params.navigation.links]
                network   = "About"
                services  = "Practice sessions"
                about     = "Restorative circles"
                contact   = "Mailing list"

        # Hero section
            [languages.en.params.hero]
                # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
                slogan     = "Restore Cph is a network for restorative circles and justice in Copenhagen"
        
        # About section
            [languages.en.params.network]
                headline    = "About Restore Cph"
                description = "We are a small network of people interested in restorative circles anchored in Copenhagen. We want a form of justice based on other principles than punishment for transgressing laws and see ourselves as part of <a href=https://www.restorativecircles.org/ target=_blank>a growing international community</a> with such a vision. Our network was born after a practical weekend seminar on restorative circles in Folkets Hus, N√∏rrebro, in the fall of 2018. We are still a new network and at this moment focus mainly on providing a space for training and apprenticeship. This takes place in the monthly practice sessions as well as our network meetings every third month where we explore a larger theme like what it takes to establish a restorative system in the specific context you find yourself in. <br><br>The network is also a space to get feedback on the challenges each of us face in facilitating circles or establishing a restorative culture where we are. You can become a member of the network by showing up to a practice session or by signing up for the mailing list.<br><br> Do you need to call for a circle, but need folks around you willing to facilitate it? We have just begun to offer facilitation services and workshops. Contact us on the email below to see if we can work together. Alternatively, we can also refer you to [Di Ponti's restorative practice](https://genoprettendepraksis.dk/)."
                #buttonText  = "Practice sessions"

            [languages.en.params.about]
                headline    = "What are restorative circles?"
                description = "Restorative circles developed in Rio de Janeiro in the middle of the 90s as a way for communities to support those who are in conflict. The circles bring the three conflicting parties together ‚Äì those who have acted, those who are directly affected by the action as well as the community around them ‚Äì¬†and in such a way that all parties are heard.<br><br>The participants invite each other and come to the circle voluntarily. The frame of the process shared openly with all participants and is guided by a member of the community. The circle ends when the parties have decided which actions could benefit everyone involved. Restorative circles are facilitated in three stages with the goal of understanding the central parts of the conflict, to reach an agreement on where to go from here and, finally, evaluate the results. The circles promote a shared power, common understanding, responsibility and action. <br><br>Would you like to know more? We believe it is best to learn this practice in a space where one can ask questions. Come for one of the monthly practice sessions and try it out. You can learn more below."
                # buttonText  = "L√¶s mere her"

        # Service section
            [languages.en.params.services]
                headline = "üôÉ"

            [[languages.en.params.services.list]]
                # icon = "fa-diamond"
                title = "Monthly"
                description = "Every month we host a practice session where we semi-simulate the process of a restorative circle."

            [[languages.en.params.services.list]]
                #icon = "fa-paper-plane"
                title = "Circle training"
                description = "One person practices the role of facilitation and the rest practices being parties to a conflict. The training takes 2,5 hours incl. evaluation."

            [[languages.en.params.services.list]]
                #icon = "fa-newspaper-o"
                title = "Open for all"
                description = "Trainings are open for all regardless of experience. Is this your first time, we would like you to come half an hour early and get a short theoretical introduction."

            [[languages.en.params.services.list]]
                #icon = "fa-heart"
                title = "If you are new"
                description = "If it is your first time, let us know via the mail below."

        # Contact section
            [languages.en.params.contact]
                headline = "If you want to learn more"
                description = "We host monthly practice sessions where anyone can participate and learn the technical skills required by restorative circles. Write us if you have any questions or tell us if you want to sign up for our mail list, then we'll let you know about coming dates."

# DANSK VERSION

        # Navigation
	       [params.navigation]
		      brand = "Genopret Kbh"

		[params.navigation.links]
            network   = "Om netv√¶rket"			
            services  = "√òve-sessions"
            about     = "Genoprettende cirkler"
			contact   = "Mailliste"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Genopret Kbh er et netv√¶rk for genoprettende cirkler og retf√¶rdighed i K√∏benhavn"
		subtitle   = ""
		buttonText = ""


	# About section
	[params.network]
		headline    = "Om Genopret Kbh"
		description = "Vi er et lille netv√¶rk af mennesker med interesse for genoprettende cirkler og en forankring i K√∏benhavn. Vi √∏nsker en retf√¶rdighed der baserer sig p√• andre principper end straf for lovovertr√¶delse og ser os som en del af <a href=https://www.restorativecircles.org/ target=_blank>et voksende internationalt f√¶llesskab</a> der netop har denne vision. Netv√¶rket opstod efter et praktisk weekendseminar om genoprettende cirkler i Folkets Hus, efter√•ret 2018. Vi er stadig et nyt netv√¶rk og har forel√∏bigt fokus p√• at tilbyde et rum for tr√¶ning og opl√¶ring. Det sker bl.a. til de m√•nedlige √∏ve-sessions samt netv√¶rksm√∏derne hver tredje m√•ned, hvor vi unders√∏ger et st√∏rre tema, fx hvad der skal til for at etablere et genoprettende system d√©r hvor man er. <br><br>Netv√¶rket er ogs√• et sted for at f√• feedback om de udfordringer vi hver is√¶r har med at facilitere cirkler eller oprette en genoprettende kultur d√©r hvor vi er. Du kan blive en del af netv√¶rket ved at komme til tr√¶ning eller tilmelde dig mailinglisten.<br><br> Har du brug for at indkalde til en cirkel og mangler folk omkring dig, der er villige til at facilitere den? Vi har for nyligt begyndte at tilbyde hj√¶lp til facilitering og workshops. Kontakt os p√• nedenst√•ende mail s√• vi kan se om vi kan arbejde sammen. Ellers kan vi ogs√• henvise til [Di Ponti's genoprettende praksis](https://genoprettendepraksis.dk/)."
		#buttonText  = "Se √∏ve-sessions"

	[params.about]
		headline    = "Hvad er genoprettende cirkler?"
		description = "Genoprettende cirkler udviklede sig i Rio de Janeiro i midten af 90'erne som en m√•de, hvorp√• f√¶llesskaber kan st√∏tte dem, der er i konflikt. Cirklerne bringer de tre konfliktende parter sammen ‚Äì den der har handlet, den der er direkte ber√∏rt af handlingen og f√¶llesskabet omkring ‚Äì og p√• en s√•dan m√•de, at alle parter bliver h√∏rt.<br><br>Deltagerne inviterer hinanden og indg√•r i kredsen frivilligt. Processens rammer er delt √•bent med alle deltagere og vejledes af et medlem af f√¶llesskabet. Forl√∏bet afsluttes n√•r parterne har bestemt hvilke handlinger der kunne gavne de indblandede. Genoprettende cirkler faciliteres i tre stadier, hvis form√•l er at forst√• de centrale dele af konflikten, at opn√• enighed om hvad der m√• ske fra nu af og s√• evaluere resultaterne. Cirklerne fremmer en delt kraft, f√¶lles forst√•else, ansvar og handling. <br><br>Vil du vide mere? Vi mener man bedst l√¶rer praksissen i rum, hvor der kan stilles sp√∏rgsm√•l. Kom til en af de m√•nedlige √∏ve-sessions og pr√∏v det af. Se mere forneden."
		# buttonText  = "L√¶s mere her"

	# Service section
	[params.services]
		headline = "√òve-sessions"

        [[params.services.list]]
            # icon = "fa-diamond"
            title = "M√•nedligt"
            description = "Hver m√•ned afholder vi √∏ve-sessions, hvor vi simulerer processen med en genoprettende cirkel."

        [[params.services.list]]
			#icon = "fa-paper-plane"
			title = "Cirkeltr√¶ning"
			description = "√ân √∏ver sig i at facilitere og resten af gruppen √∏ver sig i at v√¶re parter i en konflikt. Den simulerede cirkel tager 2¬Ω time inkl. evaluering."

		[[params.services.list]]
            #icon = "fa-newspaper-o"
            title = "√Öbent for alle"
            description = "Tr√¶ningen er √•ben for alle uden forudg√•ende erfaring. Er man ny, skal man komme en halv time tidligere og f√• en kort teoretisk indf√∏ring."

        [[params.services.list]]
            #icon = "fa-heart"
            title = "Hvis du er ny"
            description = "Giv besked, hvis du er ny p√• mailen forneden."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Hvis du vil l√¶re mere"
		description = "Vi afholder m√•nedlige √∏ve-sessions, hvor alle kan deltage og l√¶re de tekniske f√¶rdigheder som genoprettende cirkler kr√¶ver. Skriv til os og kom p√• maillisten, s√• f√•r du besked om kommende datoer."
		# phone = "123-456-6789"
		# email = "mail@mail.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	 	maps_api_key = ""
